### ISSUE TITLE
Infos

### ISSUE THREAD

**Issue by williamdes** [phptailors/docker-doctum#3]
Well this repository is not bad ! :tada: 
I realised I forgot to sha256sum check my release file in https://github.com/sudo-bot/action-doctum/blob/main/docker/Dockerfile#L11 but it is done in https://github.com/sudo-bot/action-doctum/blob/main/docker/entrypoint.sh#L19

Feel free to copy and source the copied code here.

I would accept a pull-request to add your docker image in the Doctum readme.

https://github.com/sudo-bot/action-doctum

https://github.com/sudo-bot/action-doctum/blob/main/docker/Dockerfile

**Comment by williamdes** [comment]
For your own safety please use https://github.com/code-lts/doctum#installation
https://doctum.long-term.support/releases/5/doctum.phar instead of https://doctum.long-term.support/releases/latest/doctum.phar

**Comment by ptomulik** [comment]
> [...]I realised I forgot to sha256sum check my release file in https://github.com/sudo-bot/action-doctum/blob/main/docker/Dockerfile#L11 but it is done in https://github.com/sudo-bot/action-doctum/blob/main/docker/entrypoint.sh#L19
> 
> Feel free to copy and source the copied code here.
> 

Thanks! :)

> I would accept a pull-request to add your docker image in the Doctum readme.
> 
> https://github.com/sudo-bot/action-doctum
> 
> https://github.com/sudo-bot/action-doctum/blob/main/docker/Dockerfile

I think, I have some work in front, as my docker image tags here seem to be a kind of nonsense :). I tag images with PHP version, followed by useless OS name in tag. Need to revise it first before making it public :)

**Comment by williamdes** [comment]
I will be happy to review PRs if you mention me ;)

**Comment by ptomulik** [comment]
I've reworked tagging. Now images are tagged with ``X.Y-phpV.Z`` with ``X.Y`` being doctum version and ``V.Z`` being php version. Currently ``5.3-php7.4`` and ``5.3-php8.0`` are available. ``latest`` is set to ``5.3-php7.4``.

**Comment by williamdes** [comment]
By the way, do not provide PHP 8.0 versions using the phar :pray: (this is why I pushed https://github.com/sudo-bot/action-doctum/commit/46add7568d90c70fa57d29127e44e4bb925edbfd)
This will not work, I will have to choose to drop PHP 7.1 support on the PHAR to be able to support PHP 8.0 :man_shrugging:

**Comment by ptomulik** [comment]
Removed 8.0 in https://github.com/phptailors/docker-doctum/commit/33d175a032a8fde87f915865d1cead6091e71bb2

**Comment by williamdes** [comment]
Doctum 5.3.0 is out ;) :rocket:

**Comment by ptomulik** [comment]
Works well. Thanks!

**Comment by ptomulik** [comment]
I believe, all issues mentioned here are addressed for now. I've also opened [discussion](https://github.com/phptailors/docker-doctum/discussions).

**Comment by williamdes** [comment]
I reviewed the action and it looks good!
Do you want that I call a hook here to trigger a build?
For example I trigger my @sudo-bot action docker hub build when a new release is sent
Are you interested?

**Comment by ptomulik** [comment]
> I reviewed the action and it looks good!

If you mean this repo, it's just a docker image.

> Do you want that I call a hook here to trigger a build?
> For example I trigger my @sudo-bot action docker hub build when a new release is sent
> Are you interested?

Tempting. Can we get back to this in 2021. ATM I'm in the place near to the borders of the Earth, with only my laptop and 50kbps link  :)

**Comment by williamdes** [comment]
> If you mean this repo, it's just a docker image.

Ah, yes, sorry for the mistake

> Tempting. Can we get back to this in 2021? ATM I'm in the place near to the edge of the Earth, with only my laptop and 50kbps link :)

:smile: Enjoy and dont fall from the earth :laughing: 
We can talk about that next year for sure
