### ISSUE TITLE
Update to 5.3.1

### ISSUE THREAD

**Issue by williamdes** [phptailors/docker-doctum#5]
https://github.com/phptailors/docker-doctum/blob/0d11098b083ae7db6edf96d0a720e1478a534efb/config.py#L93

Hi,
I released 5.3.1 :rocket:

**Comment by ptomulik** [comment]
Thanks for the info. Updated & released as 0.4.2.
https://github.com/phptailors/docker-doctum/blob/3ca9bf4aff6cd252b0b504789484c66f321be214/config.py#L93
